version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/mongrel/api

file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: root